"""empty message

Revision ID: 188a67aa0b66
Revises: 88e129c06d09
Create Date: 2020-04-07 15:26:36.645190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188a67aa0b66'
down_revision = '88e129c06d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('password_hash', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'name')
    op.drop_column('user', 'last_update')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'created_on')
    # ### end Alembic commands ###
