"""empty message

Revision ID: 1f961eb65841
Revises: 188a67aa0b66
Create Date: 2020-04-09 20:14:27.975481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f961eb65841'
down_revision = '188a67aa0b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('show', sa.Boolean(), nullable=True))
    op.alter_column('house', 'pub_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('house', 'pub_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('house', 'show')
    # ### end Alembic commands ###
