"""empty message

Revision ID: 9bb29c678cc2
Revises: 1f961eb65841
Create Date: 2020-04-10 11:16:09.564120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb29c678cc2'
down_revision = '1f961eb65841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'contact',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('account', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('account', 'contact',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
